version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/python-test11  # Adjusted destination path for Ubuntu
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: /install-dependencies  # Adjusted location for installation script
      runas: root  # Ensure proper permissions for root if necessary
  AfterInstall:
    - location: /after-install # Adjusted location for after-installation script
      runas: root  # Ensure proper permissions for root if necessary
